HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin, Accept-Encoding
Access-Control-Allow-Credentials: true
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
X-Content-Type-Options: nosniff
Content-Type: application/json; charset=utf-8
Content-Length: 173
ETag: W/"ad-FSpthFcjduCRSAIIgpgMIM0Wk7g"
Date: Tue, 04 Apr 2023 15:04:31 GMT
Connection: close

{
  "id": 1,
  "title": "My First Blog Post",
  "author": "Janice Jones",
  "profiles": [
    {
      "id": 1,
      "name": "secret_name",
      "blogpostId": 1
    }
  ]
}
